kind: Secret
apiVersion: v1
metadata:
  name: quarkus-native-todo-app
  labels:
    app: quarkus-native-todo-app
    app.kubernetes.io/component: quarkus-native-todo-app
    app.kubernetes.io/instance: quarkus-native-todo-app
    app.kubernetes.io/name: quarkus-native-todo-app
    app.kubernetes.io/part-of: java-apps
    app.openshift.io/runtime: quarkus
data:
  APP_TITLE: ZGVtbw==
type: Opaque
