apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-configs
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.secretsEnv }}
  {{ .name }}: {{ .value | quote }}
  {{- end }}
