apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

commonLabels:
  app: quarkus-todo-postgres

replicas:
- name: quarkus-todo-postgres
  count: 1

patches:
- path: ./patches/deployment-env-patch.yaml

- path: ./patches/deployment-resource-patch.yaml
  target:
    kind: Deployment
    group: apps
    version: v1
    name: quarkus-todo-postgres

- path: ./patches/pvc-storage-patch.yaml
  target:
    kind: PersistentVolumeClaim
    group: ""
    version: v1
    name: quarkus-todo-postgres

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: quarkus-todo-postgres-configs
    envs:
    - ./resources/02-secrets.env
    options:
      labels:
        app: quarkus-todo-postgres

images:
- name: registry.redhat.io/rhel9/postgresql-15
  newName: registry.redhat.io/rhel9/postgresql-15
  newTag: "latest"

# namePrefix: 
# nameSuffix: 
