kind: Deployment
apiVersion: apps/v1
metadata:
  name: quarkus-jvm-todo-app
spec:
  template:
    spec:
      containers:
        - name: quarkus-jvm-todo-app
          env:
            - name: APP_TITLE
              valueFrom:
                secretKeyRef:
                  name: quarkus-jvm-todo-app-configs
                  key: APP_TITLE
            - name: WELCOME_IMAGE
              valueFrom:
                secretKeyRef:
                  name: quarkus-jvm-todo-app-configs
                  key: WELCOME_IMAGE
            - name: POSTGRES_DB_URL
              valueFrom:
                secretKeyRef:
                  name: quarkus-jvm-todo-app-configs
                  key: POSTGRES_DB_URL
            - name: POSTGRES_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: quarkus-jvm-todo-app-configs
                  key: POSTGRES_DB_USERNAME
            - name: POSTGRES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quarkus-jvm-todo-app-configs
                  key: POSTGRES_DB_PASSWORD
