kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-todo-quarkus
  labels:
    app: postgres-todo-quarkus
    app.kubernetes.io/component: postgres-todo-quarkus
    app.kubernetes.io/instance: postgres-todo-quarkus
    app.kubernetes.io/name: postgres-todo-quarkus
    app.openshift.io/runtime: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem