kind: Secret
apiVersion: v1
metadata:
  name: postgres-todo-quarkus-configs
data:
  POSTGRESQL_DATABASE: cXVhcmt1cy10b2RvLWFwcA==
  POSTGRESQL_USER: cXVhcmt1cy1hZG1pbg==
  POSTGRESQL_PASSWORD: cXVhcmt1cy1hZG1pbg==
type: Opaque