# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/mukeshs1306/quarkus-jvm-todo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels:
  app: quarkus-todo-app

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
# readinessProbe:
  # httpGet:
  #   path: /
  #   port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

secretsEnv:
  - name: POSTGRES_DB_URL
    value: jdbc:postgresql://quarkus-todo-postgres.postgresdb-demo.svc.cluster.local:5432/quarkus-todo
  - name: POSTGRES_DB_USERNAME
    value: quarkus-admin
  - name: POSTGRES_DB_PASSWORD
    value: quarkus-admin
  - name: APP_TITLE
    value: quarkus-helm
  - name: WELCOME_IMAGE
    value: ./images/sample-img.png