apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

- ../../base

- ./resources/04-route.yaml

commonLabels:
  app: quarkus-jvm-todo-app

replicas:
- name: quarkus-jvm-todo-app
  count: 1

patches:
- path: ./patches/deployment-env-patch.yaml

- path: ./patches/deployment-resource-patch.yaml
  target:
    kind: Deployment
    group: apps
    version: v1
    name: quarkus-jvm-todo-app

- path: ./patches/route-service-patch.yaml
  target:
    kind: Route
    group: route.openshift.io
    version: v1
    name: quarkus-jvm-todo-app

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: quarkus-jvm-todo-app-configs
    envs:
    - ./resources/01-secrets.env
    options:
      labels:
        app: quarkus-jvm-todo-app

images:
- name: quay.io/mukeshs1306/quarkus-jvm-todo
  newName: quay.io/mukeshs1306/quarkus-jvm-todo
  newTag: "v1.0"
