apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./manifests/01-pvc.yaml
- ./manifests/03-deployment.yaml
- ./manifests/04-service.yaml

commonLabels:
  app: quarkus-todo-postgres
